export const BASE_IMG_URL = 'https://img-c.udemycdn.com/course/240x135/1565838_e54e_18.jpg'

export const COURSES = [
    {
        id: 1,
        name: "Curso de Programación Web",
        description: "Aprende a desarrollar aplicaciones web modernas con HTML, CSS y JavaScript",
        price: 89.99,
        duration: 120,
        image: BASE_IMG_URL,
    },
    {
        id: 2,
        name: "Introducción a Python",
        description: "Domina los fundamentos de Python desde cero. Ideal para principiantes",
        price: 49.99,
        duration: 80,
        image: BASE_IMG_URL,
    },
    {
        id: 3,
        name: "Diseño Gráfico Profesional",
        description: "Crea diseños impactantes usando Photoshop, Illustrator y Figma",
        price: 129.99,
        duration: 150,
        image: BASE_IMG_URL,
    },
    {
        id: 4,
        name: "Marketing Digital Completo",
        description: "Estrategias de marketing en redes sociales, SEO y publicidad online",
        price: 99.99,
        duration: 100,
        image: BASE_IMG_URL,
    },
    {
        id: 5,
        name: "React.js Avanzado",
        description: "Construye aplicaciones complejas con React, hooks y context API",
        price: 149.99,
        duration: 180,
        image: BASE_IMG_URL,
    },
    {
        id: 6,
        name: "Inglés para Negocios",
        description: "Mejora tu inglés profesional con enfoque en comunicación empresarial",
        price: 79.99,
        duration: 90,
        image: BASE_IMG_URL,
    },
    {
        id: 7,
        name: "Machine Learning con TensorFlow",
        description: "Implementa modelos de inteligencia artificial y aprendizaje automático",
        price: 199.99,
        duration: 200,
        image: BASE_IMG_URL,
    },
    {
        id: 8,
        name: "Fotografía Digital",
        description: "Técnicas profesionales de fotografía, composición y edición",
        price: 69.99,
        duration: 60,
        image: BASE_IMG_URL,
    },
    {
        id: 9,
        name: "Desarrollo de Apps Móviles",
        description: "Crea aplicaciones para iOS y Android con React Native",
        price: 159.99,
        duration: 160,
        image: BASE_IMG_URL,
    },
    {
        id: 10,
        name: "Gestión de Proyectos con Agile",
        description: "Metodologías ágiles, Scrum y Kanban para equipos de desarrollo",
        price: 119.99,
        duration: 110,
        image: BASE_IMG_URL,
    },
    {
        id: 11,
        name: "Ciberseguridad y Ethical Hacking",
        description: "Protege sistemas y aprende técnicas de hacking ético",
        price: 179.99,
        duration: 170,
        image: BASE_IMG_URL,
    },
    {
        id: 12,
        name: "Excel Avanzado y Análisis de Datos",
        description: "Domina fórmulas complejas, tablas dinámicas y visualización de datos",
        price: 59.99,
        duration: 70,
        image: BASE_IMG_URL,
    },
    {
        id: 13,
        name: "Node.js y Express",
        description: "Desarrollo de servidores y APIs RESTful con Node.js",
        price: 139.99,
        duration: 140,
        image: BASE_IMG_URL,
    },
    {
        id: 14,
        name: "Diseño UX/UI",
        description: "Principios de experiencia y diseño de interfaces de usuario",
        price: 109.99,
        duration: 130,
        image: BASE_IMG_URL,
    },
    {
        id: 15,
        name: "Blockchain y Criptomonedas",
        description: "Entiende la tecnología blockchain y el desarrollo de smart contracts",
        price: 189.99,
        duration: 190,
        image: BASE_IMG_URL,
    },
    {
        id: 16,
        name: "Video Marketing y YouTube",
        description: "Crea contenido viral, edita videos profesionales y haz crecer tu canal",
        price: 89.99,
        duration: 95,
        image: BASE_IMG_URL,
    },
    {
        id: 17,
        name: "Base de Datos SQL y NoSQL",
        description: "Aprende MySQL, PostgreSQL, MongoDB y optimización de consultas",
        price: 129.99,
        duration: 125,
        image: BASE_IMG_URL,
    },
    {
        id: 18,
        name: "Emprendimiento Digital",
        description: "De la idea al negocio: estrategias para startups y emprendimientos online",
        price: 99.99,
        duration: 105,
        image: BASE_IMG_URL,
    },
    {
        id: 19,
        name: "Docker y Kubernetes",
        description: "Containerización y orquestación de aplicaciones en la nube",
        price: 169.99,
        duration: 165,
        image: BASE_IMG_URL,
    },
    {
        id: 20,
        name: "Copywriting y Redacción Publicitaria",
        description: "Escribe textos persuasivos que convierten visitantes en clientes",
        price: 79.99,
        duration: 85,
        image: BASE_IMG_URL,
    }
]